# Generated by Django 5.2.1 on 2025-06-16 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_managed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_password_autoset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_password_expired',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('fa12d53b-103d-400f-b8f1-564234e925c4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
