# Generated by Django 5.2.1 on 2025-06-17 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_created_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('d96335f7-fb1e-4e3b-860e-10976c8ae238'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
