# Generated by Django 5.2.1 on 2025-06-17 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_driver_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('c50741cd-87eb-4349-8106-d0b51867aa30'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
