# Generated by Django 5.2.1 on 2025-06-17 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('a382a9ff-2521-4dbb-8a73-5c7bf4a3c064'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
