# Generated by Django 5.2.1 on 2025-06-17 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('5cdb3430-d26b-4f15-beb5-a8fcf667714e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
