# Generated by Django 5.2.1 on 2025-06-17 16:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('c5ecf760-bb47-44bc-8d92-4215fe523f93'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
