# Generated by Django 5.2.1 on 2025-06-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='distance_km',
            new_name='distance',
        ),
    ]
