# Generated by Django 5.2.1 on 2025-06-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_alter_ride_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='deleted_at',
        ),
    ]
