# Generated by Django 5.2.1 on 2025-06-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_remove_ride_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_at',
            field=models.DateTimeField(null=True),
        ),
    ]
