# Generated by Django 5.2.1 on 2025-06-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_ride_end_at_ride_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
